# Generated by Django 6.0.2 on 2026-02-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='کد درس'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام درس'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='required_for', to='course.course', verbose_name='پیش\u200cنیازها'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.PositiveIntegerField(verbose_name='ترم پیشنهادی چارت'),
        ),
        migrations.AlterField(
            model_name='course',
            name='units',
            field=models.PositiveIntegerField(default=3, verbose_name='تعداد واحد'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='passed_courses',
            field=models.ManyToManyField(blank=True, related_name='passed_by_students', to='course.course', verbose_name='دروس پاس شده'),
        ),
    ]
