# Generated by Django 6.0.2 on 2026-02-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_creator_alter_course_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogress',
            name='is_setup_complete',
            field=models.BooleanField(default=False, verbose_name='تکمیل تنظیمات اولیه'),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='use_default_chart',
            field=models.BooleanField(default=True, verbose_name='استفاده از چارت پیش\u200cفرض'),
        ),
    ]
